document.write("<h1>The life Time Supply  Calculator</h1>");
var lays = "laycheeze";
document.write("Favorite Snack" + lays);
 document.write("<br>");
 var age = 19;
 document.write("Current Age" + age);
 document.write("<br>");
 var maxAge = 63;
 document.write("Estimated Maximum Age" + maxAge);
 document.write("<br>");
 var perDay = 1;
 document.write("Amount of snacks per Day" + perDay);
 document.write("<br>");
document.write("you will need 528 lays to last you until the ripe old age of 63");
